=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 3.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::KmipSunsetCAOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::KmipSunsetCAOutput do
  let(:instance) { Akeyless::KmipSunsetCAOutput.new }

  describe 'test an instance of KmipSunsetCAOutput' do
    it 'should create an instance of KmipSunsetCAOutput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Akeyless::KmipSunsetCAOutput)
    end
  end

  describe 'test attribute "ca_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
