=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 3.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Akeyless
  class AerospikeTargetDetails
    attr_accessor :aerospike_admin_username

    attr_accessor :aerospike_client_certificate

    attr_accessor :aerospike_client_id

    attr_accessor :aerospike_client_private_key

    attr_accessor :aerospike_client_secret

    attr_accessor :aerospike_cloud

    attr_accessor :aerospike_cluster_id

    attr_accessor :aerospike_db_server_name

    attr_accessor :aerospike_enable_mtls

    attr_accessor :aerospike_hostname

    attr_accessor :aerospike_namespace

    attr_accessor :aerospike_password

    attr_accessor :aerospike_port

    attr_accessor :aerospike_skip_server_name_validation

    attr_accessor :aerospike_ssl_connection_certificate

    attr_accessor :aerospike_ssl_connection_mode

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aerospike_admin_username' => :'aerospike_admin_username',
        :'aerospike_client_certificate' => :'aerospike_client_certificate',
        :'aerospike_client_id' => :'aerospike_client_id',
        :'aerospike_client_private_key' => :'aerospike_client_private_key',
        :'aerospike_client_secret' => :'aerospike_client_secret',
        :'aerospike_cloud' => :'aerospike_cloud',
        :'aerospike_cluster_id' => :'aerospike_cluster_id',
        :'aerospike_db_server_name' => :'aerospike_db_server_name',
        :'aerospike_enable_mtls' => :'aerospike_enable_mtls',
        :'aerospike_hostname' => :'aerospike_hostname',
        :'aerospike_namespace' => :'aerospike_namespace',
        :'aerospike_password' => :'aerospike_password',
        :'aerospike_port' => :'aerospike_port',
        :'aerospike_skip_server_name_validation' => :'aerospike_skip_server_name_validation',
        :'aerospike_ssl_connection_certificate' => :'aerospike_ssl_connection_certificate',
        :'aerospike_ssl_connection_mode' => :'aerospike_ssl_connection_mode'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aerospike_admin_username' => :'String',
        :'aerospike_client_certificate' => :'String',
        :'aerospike_client_id' => :'String',
        :'aerospike_client_private_key' => :'String',
        :'aerospike_client_secret' => :'String',
        :'aerospike_cloud' => :'Boolean',
        :'aerospike_cluster_id' => :'String',
        :'aerospike_db_server_name' => :'String',
        :'aerospike_enable_mtls' => :'Boolean',
        :'aerospike_hostname' => :'String',
        :'aerospike_namespace' => :'String',
        :'aerospike_password' => :'String',
        :'aerospike_port' => :'String',
        :'aerospike_skip_server_name_validation' => :'String',
        :'aerospike_ssl_connection_certificate' => :'String',
        :'aerospike_ssl_connection_mode' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::AerospikeTargetDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::AerospikeTargetDetails`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aerospike_admin_username')
        self.aerospike_admin_username = attributes[:'aerospike_admin_username']
      end

      if attributes.key?(:'aerospike_client_certificate')
        self.aerospike_client_certificate = attributes[:'aerospike_client_certificate']
      end

      if attributes.key?(:'aerospike_client_id')
        self.aerospike_client_id = attributes[:'aerospike_client_id']
      end

      if attributes.key?(:'aerospike_client_private_key')
        self.aerospike_client_private_key = attributes[:'aerospike_client_private_key']
      end

      if attributes.key?(:'aerospike_client_secret')
        self.aerospike_client_secret = attributes[:'aerospike_client_secret']
      end

      if attributes.key?(:'aerospike_cloud')
        self.aerospike_cloud = attributes[:'aerospike_cloud']
      end

      if attributes.key?(:'aerospike_cluster_id')
        self.aerospike_cluster_id = attributes[:'aerospike_cluster_id']
      end

      if attributes.key?(:'aerospike_db_server_name')
        self.aerospike_db_server_name = attributes[:'aerospike_db_server_name']
      end

      if attributes.key?(:'aerospike_enable_mtls')
        self.aerospike_enable_mtls = attributes[:'aerospike_enable_mtls']
      end

      if attributes.key?(:'aerospike_hostname')
        self.aerospike_hostname = attributes[:'aerospike_hostname']
      end

      if attributes.key?(:'aerospike_namespace')
        self.aerospike_namespace = attributes[:'aerospike_namespace']
      end

      if attributes.key?(:'aerospike_password')
        self.aerospike_password = attributes[:'aerospike_password']
      end

      if attributes.key?(:'aerospike_port')
        self.aerospike_port = attributes[:'aerospike_port']
      end

      if attributes.key?(:'aerospike_skip_server_name_validation')
        self.aerospike_skip_server_name_validation = attributes[:'aerospike_skip_server_name_validation']
      end

      if attributes.key?(:'aerospike_ssl_connection_certificate')
        self.aerospike_ssl_connection_certificate = attributes[:'aerospike_ssl_connection_certificate']
      end

      if attributes.key?(:'aerospike_ssl_connection_mode')
        self.aerospike_ssl_connection_mode = attributes[:'aerospike_ssl_connection_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aerospike_admin_username == o.aerospike_admin_username &&
          aerospike_client_certificate == o.aerospike_client_certificate &&
          aerospike_client_id == o.aerospike_client_id &&
          aerospike_client_private_key == o.aerospike_client_private_key &&
          aerospike_client_secret == o.aerospike_client_secret &&
          aerospike_cloud == o.aerospike_cloud &&
          aerospike_cluster_id == o.aerospike_cluster_id &&
          aerospike_db_server_name == o.aerospike_db_server_name &&
          aerospike_enable_mtls == o.aerospike_enable_mtls &&
          aerospike_hostname == o.aerospike_hostname &&
          aerospike_namespace == o.aerospike_namespace &&
          aerospike_password == o.aerospike_password &&
          aerospike_port == o.aerospike_port &&
          aerospike_skip_server_name_validation == o.aerospike_skip_server_name_validation &&
          aerospike_ssl_connection_certificate == o.aerospike_ssl_connection_certificate &&
          aerospike_ssl_connection_mode == o.aerospike_ssl_connection_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aerospike_admin_username, aerospike_client_certificate, aerospike_client_id, aerospike_client_private_key, aerospike_client_secret, aerospike_cloud, aerospike_cluster_id, aerospike_db_server_name, aerospike_enable_mtls, aerospike_hostname, aerospike_namespace, aerospike_password, aerospike_port, aerospike_skip_server_name_validation, aerospike_ssl_connection_certificate, aerospike_ssl_connection_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
