=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 3.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Akeyless
  class FileInfo
    attr_accessor :blob_storage_key

    attr_accessor :client_file_sha256

    attr_accessor :content_type

    attr_accessor :derivation_data

    attr_accessor :encrypted_blob_sha256

    attr_accessor :encrypted_size_bytes

    attr_accessor :etag_at_complete

    attr_accessor :extension

    attr_accessor :file_id

    attr_accessor :filename

    attr_accessor :plain_size_bytes

    attr_accessor :previous_active_file_info

    attr_accessor :previous_blob_storage_key

    attr_accessor :protection_key_name

    attr_accessor :protection_key_version

    attr_accessor :status

    attr_accessor :transaction_owner

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'blob_storage_key' => :'blob_storage_key',
        :'client_file_sha256' => :'client_file_sha256',
        :'content_type' => :'content_type',
        :'derivation_data' => :'derivation_data',
        :'encrypted_blob_sha256' => :'encrypted_blob_sha256',
        :'encrypted_size_bytes' => :'encrypted_size_bytes',
        :'etag_at_complete' => :'etag_at_complete',
        :'extension' => :'extension',
        :'file_id' => :'file_id',
        :'filename' => :'filename',
        :'plain_size_bytes' => :'plain_size_bytes',
        :'previous_active_file_info' => :'previous_active_file_info',
        :'previous_blob_storage_key' => :'previous_blob_storage_key',
        :'protection_key_name' => :'protection_key_name',
        :'protection_key_version' => :'protection_key_version',
        :'status' => :'status',
        :'transaction_owner' => :'transaction_owner'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'blob_storage_key' => :'String',
        :'client_file_sha256' => :'String',
        :'content_type' => :'String',
        :'derivation_data' => :'String',
        :'encrypted_blob_sha256' => :'String',
        :'encrypted_size_bytes' => :'Integer',
        :'etag_at_complete' => :'String',
        :'extension' => :'String',
        :'file_id' => :'String',
        :'filename' => :'String',
        :'plain_size_bytes' => :'Integer',
        :'previous_active_file_info' => :'FileInfo',
        :'previous_blob_storage_key' => :'String',
        :'protection_key_name' => :'String',
        :'protection_key_version' => :'Integer',
        :'status' => :'String',
        :'transaction_owner' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::FileInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::FileInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'blob_storage_key')
        self.blob_storage_key = attributes[:'blob_storage_key']
      end

      if attributes.key?(:'client_file_sha256')
        self.client_file_sha256 = attributes[:'client_file_sha256']
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'derivation_data')
        self.derivation_data = attributes[:'derivation_data']
      end

      if attributes.key?(:'encrypted_blob_sha256')
        self.encrypted_blob_sha256 = attributes[:'encrypted_blob_sha256']
      end

      if attributes.key?(:'encrypted_size_bytes')
        self.encrypted_size_bytes = attributes[:'encrypted_size_bytes']
      end

      if attributes.key?(:'etag_at_complete')
        self.etag_at_complete = attributes[:'etag_at_complete']
      end

      if attributes.key?(:'extension')
        self.extension = attributes[:'extension']
      end

      if attributes.key?(:'file_id')
        self.file_id = attributes[:'file_id']
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'plain_size_bytes')
        self.plain_size_bytes = attributes[:'plain_size_bytes']
      end

      if attributes.key?(:'previous_active_file_info')
        self.previous_active_file_info = attributes[:'previous_active_file_info']
      end

      if attributes.key?(:'previous_blob_storage_key')
        self.previous_blob_storage_key = attributes[:'previous_blob_storage_key']
      end

      if attributes.key?(:'protection_key_name')
        self.protection_key_name = attributes[:'protection_key_name']
      end

      if attributes.key?(:'protection_key_version')
        self.protection_key_version = attributes[:'protection_key_version']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'transaction_owner')
        self.transaction_owner = attributes[:'transaction_owner']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          blob_storage_key == o.blob_storage_key &&
          client_file_sha256 == o.client_file_sha256 &&
          content_type == o.content_type &&
          derivation_data == o.derivation_data &&
          encrypted_blob_sha256 == o.encrypted_blob_sha256 &&
          encrypted_size_bytes == o.encrypted_size_bytes &&
          etag_at_complete == o.etag_at_complete &&
          extension == o.extension &&
          file_id == o.file_id &&
          filename == o.filename &&
          plain_size_bytes == o.plain_size_bytes &&
          previous_active_file_info == o.previous_active_file_info &&
          previous_blob_storage_key == o.previous_blob_storage_key &&
          protection_key_name == o.protection_key_name &&
          protection_key_version == o.protection_key_version &&
          status == o.status &&
          transaction_owner == o.transaction_owner
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [blob_storage_key, client_file_sha256, content_type, derivation_data, encrypted_blob_sha256, encrypted_size_bytes, etag_at_complete, extension, file_id, filename, plain_size_bytes, previous_active_file_info, previous_blob_storage_key, protection_key_name, protection_key_version, status, transaction_owner].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
