=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 3.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module Akeyless
  class UpdateMcpSecretOAuthAuthCode
    # for personal password manager
    attr_accessor :accessibility

    # Enable or disable Agentic Runtime Authority rule enforcement for this item. When false, user-defined input/output rules are stored but not enforced; the base security validation still runs.  AraEnabled is tri-state (nil/true/false), not a plain bool: it self-encodes its wire value (see akl.OptionalBool) so an explicit false survives the curl-proxy relay instead of being dropped like a default-false bool flag.
    attr_accessor :ara_enabled

    # Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input)
    attr_accessor :input_rule

    # Set output format to JSON
    attr_accessor :json

    # Whether to keep previous version [true/false]. If not set, use default according to account settings
    attr_accessor :keep_prev_version

    attr_accessor :key

    attr_accessor :last_version

    # Secret name
    attr_accessor :name

    # OAuth client ID
    attr_accessor :oauth_client_id

    # OAuth client secret
    attr_accessor :oauth_client_secret

    # OAuth redirect URI
    attr_accessor :oauth_redirect_uri

    # OAuth refresh token
    attr_accessor :oauth_refresh_token

    # OAuth scopes
    attr_accessor :oauth_scopes

    # OAuth token URL
    attr_accessor :oauth_token_url

    # Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
    attr_accessor :output_rule

    # Authentication token (see `/auth` and `/configure`)
    attr_accessor :token

    # The universal identity token, Required only for universal_identity authentication
    attr_accessor :uid_token

    # URL of the service
    attr_accessor :url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'accessibility' => :'accessibility',
        :'ara_enabled' => :'ara-enabled',
        :'input_rule' => :'input-rule',
        :'json' => :'json',
        :'keep_prev_version' => :'keep-prev-version',
        :'key' => :'key',
        :'last_version' => :'last-version',
        :'name' => :'name',
        :'oauth_client_id' => :'oauth-client-id',
        :'oauth_client_secret' => :'oauth-client-secret',
        :'oauth_redirect_uri' => :'oauth-redirect-uri',
        :'oauth_refresh_token' => :'oauth-refresh-token',
        :'oauth_scopes' => :'oauth-scopes',
        :'oauth_token_url' => :'oauth-token-url',
        :'output_rule' => :'output-rule',
        :'token' => :'token',
        :'uid_token' => :'uid-token',
        :'url' => :'url'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'accessibility' => :'String',
        :'ara_enabled' => :'Boolean',
        :'input_rule' => :'Array<String>',
        :'json' => :'Boolean',
        :'keep_prev_version' => :'String',
        :'key' => :'String',
        :'last_version' => :'Integer',
        :'name' => :'String',
        :'oauth_client_id' => :'String',
        :'oauth_client_secret' => :'String',
        :'oauth_redirect_uri' => :'String',
        :'oauth_refresh_token' => :'String',
        :'oauth_scopes' => :'Array<String>',
        :'oauth_token_url' => :'String',
        :'output_rule' => :'Array<String>',
        :'token' => :'String',
        :'uid_token' => :'String',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::UpdateMcpSecretOAuthAuthCode` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::UpdateMcpSecretOAuthAuthCode`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'accessibility')
        self.accessibility = attributes[:'accessibility']
      else
        self.accessibility = 'regular'
      end

      if attributes.key?(:'ara_enabled')
        self.ara_enabled = attributes[:'ara_enabled']
      end

      if attributes.key?(:'input_rule')
        if (value = attributes[:'input_rule']).is_a?(Array)
          self.input_rule = value
        end
      end

      if attributes.key?(:'json')
        self.json = attributes[:'json']
      else
        self.json = false
      end

      if attributes.key?(:'keep_prev_version')
        self.keep_prev_version = attributes[:'keep_prev_version']
      end

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      end

      if attributes.key?(:'last_version')
        self.last_version = attributes[:'last_version']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'oauth_client_id')
        self.oauth_client_id = attributes[:'oauth_client_id']
      end

      if attributes.key?(:'oauth_client_secret')
        self.oauth_client_secret = attributes[:'oauth_client_secret']
      end

      if attributes.key?(:'oauth_redirect_uri')
        self.oauth_redirect_uri = attributes[:'oauth_redirect_uri']
      end

      if attributes.key?(:'oauth_refresh_token')
        self.oauth_refresh_token = attributes[:'oauth_refresh_token']
      end

      if attributes.key?(:'oauth_scopes')
        if (value = attributes[:'oauth_scopes']).is_a?(Array)
          self.oauth_scopes = value
        end
      end

      if attributes.key?(:'oauth_token_url')
        self.oauth_token_url = attributes[:'oauth_token_url']
      end

      if attributes.key?(:'output_rule')
        if (value = attributes[:'output_rule']).is_a?(Array)
          self.output_rule = value
        end
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'uid_token')
        self.uid_token = attributes[:'uid_token']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          accessibility == o.accessibility &&
          ara_enabled == o.ara_enabled &&
          input_rule == o.input_rule &&
          json == o.json &&
          keep_prev_version == o.keep_prev_version &&
          key == o.key &&
          last_version == o.last_version &&
          name == o.name &&
          oauth_client_id == o.oauth_client_id &&
          oauth_client_secret == o.oauth_client_secret &&
          oauth_redirect_uri == o.oauth_redirect_uri &&
          oauth_refresh_token == o.oauth_refresh_token &&
          oauth_scopes == o.oauth_scopes &&
          oauth_token_url == o.oauth_token_url &&
          output_rule == o.output_rule &&
          token == o.token &&
          uid_token == o.uid_token &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [accessibility, ara_enabled, input_rule, json, keep_prev_version, key, last_version, name, oauth_client_id, oauth_client_secret, oauth_redirect_uri, oauth_refresh_token, oauth_scopes, oauth_token_url, output_rule, token, uid_token, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
